import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, ShieldAlert, CheckCircle2, ChevronRight, Activity, Clock, Server } from 'lucide-react';
import { useWeb3ModalAccount } from '@web3modal/ethers/react';
import './Dashboard.css';
import './DashboardPages.css';

export default function Dashboard() {
  const [pendingIntents, setPendingIntents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [verifyingId, setVerifyingId] = useState(null);
  
  // Web3Modal Hooks
  const { address, isConnected } = useWeb3ModalAccount();
  
  const navigate = useNavigate();

  useEffect(() => {
    fetchPendingIntents();
  }, []);

  const fetchPendingIntents = async () => {
    try {
      const response = await fetch('http://localhost:8000/audit/pending');
      if (response.ok) {
        const data = await response.json();
        setPendingIntents(data.pending_intents || []);
      }
    } catch (err) {
      console.error("Error fetching pending intents", err);
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async (auditId) => {
    if (!isConnected) {
      alert("Please connect your wallet first!");
      return;
    }
    
    setVerifyingId(auditId);
    try {
      const response = await fetch('http://localhost:8000/audit/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          audit_id: auditId,
          verifier_address: address
        })
      });
      
      if (response.ok) {
        await fetchPendingIntents(); // Refresh list
        alert("Intent verified and executed successfully on HeLa Testnet!");
      } else {
        const errData = await response.json();
        alert("Verification failed: " + (errData.detail || "Unknown error"));
      }
    } catch (err) {
      console.error("Verification error", err);
      alert("An error occurred during verification.");
    } finally {
      setVerifyingId(null);
    }
  };


  return (
    <div className="page-container">
      <header className="page-header">
        <h2>Command Center</h2>
        <p>Review and verify decisions generated by autonomous agents before network execution.</p>
      </header>

      {loading ? (
          <div className="loading-state">
            <Activity className="animate-spin" size={32} color="#818cf8" />
            <p>Scanning network for pending intents...</p>
          </div>
        ) : pendingIntents.length === 0 ? (
          <div className="empty-state glass-panel">
            <CheckCircle2 size={48} color="#4ade80" style={{ marginBottom: '1rem' }} />
            <h2>All Caught Up</h2>
            <p>No pending intents require your attention at the moment.</p>
          </div>
        ) : (
          <div className="intents-grid">
            {pendingIntents.map((intent) => {
              const riskColor = intent.risk_score >= 8 ? '#ef4444' : intent.risk_score >= 5 ? '#f59e0b' : '#10b981';
              
              return (
                <div key={intent.audit_id} className="intent-card glass-panel">
                  <div className="intent-card-header">
                    <div className="intent-badges">
                      <span className="badge action-badge">{intent.action}</span>
                      <span className="badge risk-badge" style={{ backgroundColor: `${riskColor}20`, color: riskColor, border: `1px solid ${riskColor}40` }}>
                        Risk Score: {intent.risk_score}/10
                      </span>
                    </div>
                    <div className="intent-amount">
                      <span className="amount-val">{intent.amount}</span> tokens
                    </div>
                  </div>

                  <div className="intent-body">
                    <div className="info-group">
                      <label>Agent's Stated Reason:</label>
                      <p className="reason-text">"{intent.reason}"</p>
                    </div>

                    <div className="info-group ai-explanation" style={{ borderColor: `${riskColor}40` }}>
                      <label><Shield size={14} style={{ marginRight: '6px' }} /> AI Auditor Assessment</label>
                      <p>{intent.explanation}</p>
                    </div>
                  </div>

                  <div className="intent-footer">
                    <div className="intent-meta">
                      <span><Clock size={12} /> {new Date(intent.submitted_at * 1000).toLocaleTimeString()}</span>
                      <span><Server size={12} /> ID: {intent.audit_id.slice(0,8)}...</span>
                    </div>
                    
                    <button 
                      className={`verify-btn ${intent.risk_score >= 8 ? 'high-risk' : ''}`}
                      onClick={() => handleVerify(intent.audit_id)}
                      disabled={verifyingId === intent.audit_id}
                    >
                      {verifyingId === intent.audit_id ? (
                        <>Verifying... <Activity className="animate-spin" size={16} style={{ marginLeft: '8px' }}/></>
                      ) : (
                        <>Verify & Release <ChevronRight size={16} /></>
                      )}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
    </div>
  );
}
