import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, ShieldAlert, CheckCircle2, ChevronRight, Activity, Clock, Server, RefreshCw, AlertTriangle, Zap, Cpu } from 'lucide-react';
import { useWeb3Context } from '../../context/Web3Context';
import { useToast } from '../../components/Toast';
import { PageHeader } from '../../components/PageHeader';
import { StatCard } from '../../components/StatCard';
import { IntentCard } from '../../components/IntentCard';
import { AllCaughtUp } from '../../components/AllCaughtUp';
import './Dashboard.css';
import './DashboardPages.css';

export default function Dashboard() {
  const [pendingIntents, setPendingIntents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const toast = useToast();
  
  // Native Web3 Context
  const { address, isConnected } = useWeb3Context();
  
  const navigate = useNavigate();

  useEffect(() => {
    fetchPendingIntents();
    // Auto-refresh every 10 seconds
    const interval = setInterval(() => fetchPendingIntents(true), 10000);
    return () => clearInterval(interval);
  }, []);

  const fetchPendingIntents = async (silent = false) => {
    if (!silent) setLoading(true);
    else setRefreshing(true);

    try {
      const response = await fetch('http://localhost:8000/audit/pending');
      if (response.ok) {
        const data = await response.json();
        setPendingIntents(data.pending_intents || []);
      }
    } catch (err) {
      if (!silent) toast.error("Connection Error", "Failed to load pending intents from network.");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  const handleRefreshClick = () => {
    fetchPendingIntents();
    toast.info("Refreshing queue", "Checking network for new intents");
  };

  const handleVerified = () => {
    fetchPendingIntents(true);
  };

  // Compute stats
  const stats = useMemo(() => {
    const pending = pendingIntents.length;
    const critical = pendingIntents.filter(i => i.risk_score >= 8).length;
    const elevated = pendingIntents.filter(i => i.risk_score >= 5 && i.risk_score < 8).length;
    return { pending, critical, elevated, active: 12 }; // Active is mock for now
  }, [pendingIntents]);

  const mapIntentData = (item) => ({
    id: item.audit_id,
    action: item.action,
    riskScore: item.risk_score,
    amount: item.amount,
    asset: "Tokens",
    agentReason: item.reason,
    auditorAssessment: item.explanation,
    timestamp: new Date(item.submitted_at * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
  });

  return (
    <div className="page-container dashboard-page">
      <PageHeader
        eyebrow="Network Overview"
        title="Command Center"
        description="Review and verify decisions generated by autonomous agents before network execution."
        actions={
          <button 
            className="action-btn-ghost hover-lift" 
            onClick={handleRefreshClick}
            disabled={loading || refreshing}
          >
            <RefreshCw size={14} className={(loading || refreshing) ? "animate-spin" : ""} />
            Refresh queue
          </button>
        }
      />

      {/* Stats Grid */}
      <div className="dashboard-grid dashboard-grid-4-col mb-8">
        <StatCard 
          icon={Activity} 
          label="Pending Review" 
          value={stats.pending.toString()} 
          tone={stats.pending > 0 ? "warning" : "default"} 
        />
        <StatCard 
          icon={ShieldAlert} 
          label="Critical Risk" 
          value={stats.critical.toString()} 
          tone={stats.critical > 0 ? "danger" : "default"} 
        />
        <StatCard 
          icon={AlertTriangle} 
          label="Elevated Risk" 
          value={stats.elevated.toString()} 
          tone={stats.elevated > 0 ? "warning" : "default"} 
        />
        <StatCard 
          icon={Cpu} 
          label="Active Agents" 
          value={stats.active.toString()} 
          tone="success" 
        />
      </div>

      <div className="dashboard-section-header">
        <h3 className="section-title">Pending Intents Queue</h3>
        <span className="section-badge">{pendingIntents.length}</span>
      </div>

      {loading ? (
        <div className="loading-state-v2 glass">
          <div className="pulse-dot-wrapper">
            <span className="pulse-dot-ping bg-accent-light" />
            <span className="pulse-dot bg-accent-light" />
          </div>
          <p>Scanning network...</p>
        </div>
      ) : pendingIntents.length === 0 ? (
        <AllCaughtUp />
      ) : (
        <div className="dashboard-grid dashboard-grid-2-col">
          {pendingIntents.map((intent) => (
            <IntentCard 
              key={intent.audit_id} 
              intent={mapIntentData(intent)} 
              onVerified={handleVerified} 
            />
          ))}
        </div>
      )}
    </div>
  );
}
